### ISSUE TITLE
Error during assets build: Undefined variable: "$base-font-size"

### ISSUE THREAD

**Issue by yaroslavbr** [oroinc/orocommerce#140]
**Summary**  
After commerce update to 4.2 version and trying to rebuild assets with `oro:assets:install` command I getting strange error
over and over. I already tried different approaches, different composer versions, etc, symfony-flex installed, fxp-plugin - not for composer 2 (because is not supported). Maybe you can suggests something?

**Steps to reproduce**  
- update orocommerce from 4.1 to 4.2
- run `oro:assets:install`

**Actual Result**
Getting error:
`
Child default theme:
    Time: 40739ms
    PublicPath: /build/default/
     2 assets
    
    ERROR in ./build/default/css/stylebook.css.scss
    Module build failed (from ../node_modules/mini-css-extract-plugin/dist/loader.js):
    ModuleBuildError: Module build failed (from ../node_modules/sass-loader/lib/loader.js):
    
    $base-ui-element-font-size: $base-font-size;
                               ^
          Undefined variable: "$base-font-size".
          in /app/public/bundles/oroform/default/scss/settings/_variables.scss (line 4, column 29)
        at /app/node_modules/webpack/lib/NormalModule.js:316:20
        at /app/node_modules/loader-runner/lib/LoaderRunner.js:367:11
        at /app/node_modules/loader-runner/lib/LoaderRunner.js:233:18
        at context.callback (/app/node_modules/loader-runner/lib/LoaderRunner.js:111:13)
        at Object.callback (/app/node_modules/sass-loader/lib/loader.js:52:13)
        at Object.done [as callback] (/app/node_modules/neo-async/async.js:8069:18)
        at options.error (/app/node_modules/node-sass/lib/index.js:294:32)
     @ ./build/default/css/stylebook.scss.js 1:0-30`

**Expected Result**  
- Assets should be build sucessfully

**Details about your environment**
- `composer info | grep oro/
The "fxp/composer-asset-plugin" plugin (installed globally) was skipped because it requires a Plugin API version ("^1.0") that does not match your Composer installation ("2.1.0"). You may need to run composer update with the "--no-plugins" option.
The "hirak/prestissimo" plugin (installed globally) was skipped because it requires a Plugin API version ("^1.0.0") that does not match your Composer installation ("2.1.0"). You may need to run composer update with the "--no-plugins" option.
oro/calendar-bundle                  4.2.3               Calendar bundle for OroPlatform-based applications.See https://doc.oroinc.com/user/back-office/activities/calendar-events/ for more information.
oro/commerce                         4.2.5               OroCommerce - an open-source Business to Business Commerce application. \nThis package contains bundles and needs to be added as a dependency in an OroCommerce application.
oro/commerce-akeneo                  4.2.9               Akeneo PIM OroCommerce Connector.
oro/commerce-crm                     4.2.2               OroCRM integration for OroCommerce
oro/commerce-crm-ee                  4.2.4               OroCommerce OroCRM Enterprise Bridge
oro/commerce-enterprise              4.2.4               OroCommerce Enterprise.
oro/cookie-consent                   4.2.2               Oro Commerce Cookie Consent
oro/crm                              4.2.4               OroCRM
oro/crm-call-bundle                  4.2.3               Oro Call Bundle
oro/crm-dotmailer                    4.2.2               Oro Dotmailer integration
oro/crm-enterprise                   4.2.3               OroCRM Enterprise
oro/crm-hangouts-call-bundle         4.2.1               Oro Google Hangouts integration
oro/crm-magento-embedded-contact-us  4.2.0-alpha.3       OroCRM Magento Embedded Contact Us package
oro/crm-pro-ldap-bundle              4.2.1               OroCRM Pro LDAP Bundle
oro/crm-task-bundle                  4.2.2               Oro Task Bundle
oro/crm-zendesk                      4.2.2               OroCRM Zendesk Integration
oro/customer-portal                  4.2.4              
oro/doctrine-extensions              2.0.0               Doctrine Extensions for MySQL and PostgreSQL.
oro/google-tag-manager-bundle        4.2.1               Oro Google Tag Manager integration
oro/gridfs-config                    4.2.2               GridFS adapter configuration for Gaufrette
oro/health-check-bundle              4.2.2               Oro Health Check Bundle
oro/marketing                        4.2.4               Oro Marketing Bundles
oro/multi-host                       4.2.3               Oro Multi-Host deployment support for BAP
oro/oauth2-server                    4.2.4               Oro OAuth 2.0 authorization and resource server for BAP
oro/platform                         4.2.5               Business Application Platform (BAP)
oro/platform-enterprise              4.2.4               OroPlatform Enterprise
oro/platform-serialised-fields       4.2.3               OroPlatform Serialized Fields
oro/redis-config                     4.2.2               OroRedisConfigBundle
oro/twig-inspector                   1.0.3               Oro Twig Inspector adds the possibility to find twig templates and blocks used for rendering HTML pages faster during development
`
- PHP version: PHP 7.4.22 
- Database PostgreSQL 12

- [Optional] Server operating system : Ubuntu
**Additional information**

**Comment by ValeriyYustunyk** [comment]
Try to add missed setting to stylebook styles into `assets.yml` like 
```yml
stylebook_styles:
    inputs:
        - 'bundles/orocustomtheme/FrontendBundle/scss/settings/main/global-settings.scss'
    output: 'css/stylebook.css'
```
You might find such an example in [custom theme](https://github.com/oroinc/orocommerce/blob/master/src/Oro/Bundle/CustomThemeBundle/Resources/views/layouts/custom/config/assets.yml#L36-L39).

**Comment by yaroslavbr** [comment]
@ValeriyYustunyk the problem is that these variables are oro internal variables, and as I can see there is already such instruction for global-settings.scss which should include it. I also tried to add such block in my custom assets.yml but getting same error again and again.

**Comment by ValeriyYustunyk** [comment]
Looks like is customization was removed `$base-font-size` variable.
Did you try to bind styles without your customization?
I mean hide (comment, revert) all your own styles in `assets.yml`.

**Comment by yaroslavbr** [comment]
I tried to revert everything as possible. Regarding the variable - $base-font-size - it is defined in oro code, and there are no customizations regarding it. For now  I find out one interesting thing, seems the problem is in the includes order:
`@import "./../../../bundles/oroform/default/scss/settings/global-settings";
@import "./../../../bundles/orofrontend/default/scss/settings/global-settings";
@import "./../../../bundles/orofrontend/default/scss/settings/bootstrap/variables";
@import "./../../../bundles/orofrontend/default/scss/settings/global-settings";
@import "./../../../bundles/orocustomer/default/scss/settings/global-settings";
@import "./../../../bundles/oroform/blank/scss/settings/mixins/appearance";
@import "./../../../bundles/madiafrontend/crh_theme/scss/settings/main/global-settings";
@import "./../../../bundles/madiafrontend/crh_theme/scss/settings/_mixins";
@import "./../../../bundles/madiafrontend/crh_theme/scss/settings/main/global-settings";
@import "./../../../bundles/madiatheme/scss/settings/partials/_sizes";
@import "./../../../bundles/madiatheme/scss/settings/main/_fluid";
@import "./../../../bundles/madiaui/crh_theme/scss/settings/global-settings";
@import "./../../../bundles/madiafrontend/crh_theme/scss/settings/main/global-settings";
@import "./../../../bundles/madiafrontend/crh_theme/scss/settings/_mixins";
@import "./../../../bundles/madiafrontend/crh_theme/scss/settings/main/global-settings";
@import "./../../../bundles/madiatheme/scss/settings/partials/_sizes";
@import "./../../../bundles/orocustomtheme/FrontendBundle/scss/settings/main/global-settings";
@import "./../../../bundles/oroform/default/scss/settings/global-settings";
@import "./../../../bundles/oroui/blank/scss/settings/global-settings";`

Seems variable defined in file which is included later

**Comment by ValeriyYustunyk** [comment]
One import is missed above of `@import "./../../../bundles/oroform/default/scss/settings/global-settings"` should be included 
`@import "./../../../bundles/oroui/blank/scss/settings/global-settings"`.

**Comment by yaroslavbr** [comment]
yes, it is included in the end of the list that I send, somehow. So researching why it is that and how can I handle it, maybe play with bundle priorities
